/*
 *********************************************************************************
 *     Copyright (c) 2014	ASIX Electronic Corporation      All rights reserved.
 *
 *     This is unpublished proprietary source code of ASIX Electronic Corporation
 *
 *     The copyright notice above does not evidence any actual or intended
 *     publication of such source code.
 *********************************************************************************
 */
/*================================================================================
 * Module Name : spim.h
 * Purpose     : A header file of SPI master registers. It defines register address and bits.
 * Author      : 
 * Date        : 
 * Notes       :
 *================================================================================
 */
#ifndef SPIM_H
#define SPIM_H

/* INCLUDE FILE DECLARATIONS */


/* NAMING CONSTANT DECLARATIONS */
/* SPI Master Controller Register Map*/
#define SPICMR					0x00 // SPI Control Register
#define SPIBRR					0x01 // SPI Baud Rate Register
#define SPIMCSR					0x02 // SPI Slave Select Register
#define SPIMISR					0x03 // SPI Master Interrupt Status Register
#define SPIMIER					0x04 // SPI Master Interrupt Enable Register
#define SPIDS					0x05 // SPI Delay before SCLK
#define SPIDT					0x06 // SPI Delay Transmission
#define SDCR					0x07 // SPI DMA Command Register
#define SDTSA					0x08 // SPI DMA TX Starting Address
#define SDTBC					0x0A // SPI DMA TX Byte Count
#define SDRSA					0x0C // SPI DMA RX Starting Address
#define SDRBC					0x0E // SPI DMA RX Byte Count
#define SDFL					0x10 // SPI DMA Fragment Length
#define SDAOF					0x12 // SPI Delay After Op-code Field
#define	STOL					0x13 // SPI Transfer OP-Code Length
#define STOF					0x14 // SPI Transfer OP-Code Field

/* Master Mode */
/* SPICMR 0x00*/
#define	SPICMR_SSP_HIGH			BIT0	// slave select is high active
#define	SPICMR_SSP_LOW			0		// slave select is low active
#define	SPICMR_CPHA_BEG			BIT1	// spi first clock edge is issued at the beginning of transfer cycle
#define	SPICMR_CPHA_HALF		0		// spi first clock edge is issued one-half cycle of transfer cycle
#define	SPICMR_CPOL_LOW			BIT2	// clock active low
#define	SPICMR_CPOL_HIGH		0		// clock active high
#define	SPICMR_BIT_LSB			BIT3	// LSB bit transmit/receive first
#define	SPICMR_BIT_MSB			0		// MSB bit transmit/receive first
#define	SPICMR_MST_ENB			BIT4	// spi master module enable
#define	SPICMR_MST_DISB			0		// spi master module disable
#define	SPICMR_ASS_AUTO			BIT5	// slave select signal generated automatically
#define	SPICMR_ASS_NORM			0		// slave select signal generated by SPISSR bits
#define	SPICMR_SSOE_ENB			BIT7	// enable driving slave select signal
#define	SPICMR_SSOE_DISB		0		// put slave select signal to tri-state
#define	SPICMR_MODE0			(SPICMR_CPHA_HALF | SPICMR_CPOL_HIGH)
#define	SPICMR_MODE1			(SPICMR_CPHA_HALF | SPICMR_CPOL_LOW)
#define	SPICMR_MODE2			(SPICMR_CPHA_BEG | SPICMR_CPOL_HIGH)
#define	SPICMR_MODE3			(SPICMR_CPHA_BEG | SPICMR_CPOL_LOW)


/* SPISSR 0x02 */
/* For Master Select */
#define	SPISSR_SS0				(BIT2 | BIT1)
#define	SPISSR_SS1				(BIT2 | BIT0)
#define	SPISSR_SS2				(BIT1 | BIT0)
#define	SPISSR_EDE_SS0			0x00
#define SPISSR_EDE_SS1			0x01
#define SPISSR_EDE_SS2			0x02
#define SPISSR_EDE_SS3			0x03
#define SPISSR_EDE_SS4			0x04
#define SPISSR_EDE_SS5			0x05
#define SPISSR_EDE_SS6			0x06
#define	SPISSR_EDE_ENB			BIT7
#define SPISSR_EDE_DISB			0

/* SPIMISR 0x03 */
#define SPIMISR_SDTCS			BIT0	// SPI DMA Transceiver Complete Status
#define SPIMISR_DMAERRS			BIT1	// DMA Error indication Status

/* SPIMIER 0x04 */
#define	SPIMIER_SDTCFIE_ENB		BIT0	// SPI DMA Transceiver Complete Flag Interrupt Enable
#define	SPIMIER_SDTCFIE_DISB	0	    // SPI DMA Transceiver Complete Flag Interrupt Disable
#define	SPIMIER_DMAERRIE_ENB	BIT1	// SPI DMA error Enable
#define	SPIMIER_DMAERRIE_DISB	0		// SPI DMA error Disable

/* SDCR 0x07 */
#define	SDCR_ETDMA_EXC			BIT0	// SPI Execute TX DMA
#define SDCR_ETDMA_IDL			0		// TX DMA idle.
#define	SDCR_ERDMA_EXC			BIT1	// SPI Execute RX DMA
#define SDCR_ERDMA_IDL			0		// RX DMA idle
#define SDCR_OPC_ENB			BIT2	// OP-Code Field Enable
#define SDCR_OPC_DISB			0
#define	SDCR_DMA_GO				BIT4	// Starts the burst-type transfer via DMA mode
#define SDCR_FBT_ENB			BIT5	// Fragment Burst-type Transfer Enable
#define SDCR_FBT_DISB			0
#define SDCR_CSS_CONT			BIT6	// Continuous Slave Select
#define SDCR_CSS_NOT			0

/* SPI Master Flag*/
#define SPI_DMA_TXRX_CPL		BIT0

typedef	struct {
	U8_T		IntrEnb;
	U8_T		IntrStatus;
	U8_T		ActFlag;
} SPI_MST_INST_T;

/* MACRO DECLARATIONS */

/* TYPE DECLARATIONS */


/* GLOBAL VARIABLES */


/* EXPORTED SUBPROGRAM SPECIFICATIONS */
void 	SPI_MstRegWrite(U8_T addr, U8_T *ptData, U8_T dataLen);
void 	SPI_MstRegRead(U8_T addr, U8_T *ptData, U8_T dataLen);

void	SPI_MstModeSetup(U8_T ctrlCmd, U8_T intrEnb, U8_T baudrate, U8_T opDelay, U8_T slvSel);
void	SPI_MstDmaSetting(U8_T dbs, U8_T dt);
void	SPI_SetOpCodeReg(U8_T* opCode, U8_T opLen);
BOOL	SPI_IsMstSpiBusRdy(void);
void	SPI_MstDmaTx(U8_T *txStrAddr, U16_T txByteCnt, U8_T cmd);
void	SPI_MstDmaRx(U8_T *rxStrAddr, U16_T rxByteCnt, U8_T cmd);
void	SPI_MstSendOpOnly();
void	SPI_MstFlagEnb(U8_T	flag);
BOOL	SPI_MstFlagChk(U8_T	flag);
#endif /* End of SPIM_H */